{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{default .Values.app.namespace .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.server }}
    privateKeySecretRef:
      name: {{ .Values.issuer.privateKeySecretRef.name }}
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end -}}