{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{default .Values.app.fullnameOverride .Release.Name }}-ingress
  namespace: {{default .Values.app.namespace .Release.Namespace }}
  annotations:
    cert-manager.io/issuer: {{ .Values.issuer.name }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - backend:
          service:
            name: {{default .Values.app.fullnameOverride .Release.Name }}-service
            port:
              number: {{ .Values.ingress.portNumber }}
        path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{default .Values.app.fullnameOverride .Release.Name }}-ingress
# spec:
#   rules:
#   - host: {{ .Values.ingress.hostName }}
#     http:
#       paths:
#       - backend:
#           service:
#             name: {{default .Values.app.fullnameOverride .Release.Name }}-service
#             port:
#               number: {{ .Values.ingress.portNumber }}
#         path: {{ .Values.ingress.path }}
#         pathType: {{ .Values.ingress.pathType }}
#   ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end -}}

