apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-ecr-secret
  namespace: {{default .Values.app.namespace .Release.Namespace }}
spec:
  encryptedData:
    .dockerconfigjson: AgCvAJjWDMJ0tHVaLjMaHdaJMVLTTYMJDebsBJlFlWVwxJLdP061MDUN8MQwyevUOxzXihNiCppIClAhJcuVkTkJrhZFscZtVIJW9oe13WjmnkJJ7urJfv2A8vDO6i881/yskbu/K/ukjxi04wChdHL0BjT4uOTRa5Rxph4+KQyCJpUbDM+pGGEoU25szLD6qQJLtDev2P1ZwLEupcLKKHJMfDL9c9hXRehDBwv2XeWdv8PnON3EE49H6JOySTjqFBeozd6Vh9w/xNcwAlzO1DQb+5DhhHBogAmz3DbBVT+XQ4Y9mFpQS/KCQWr+S2TV9TlO5obPoBlCVPRZWUabuKL1/pNIgxExqp7Ce2HUmjHybhDnLPPJb4wY+reFh8lFLlU3mcdX/kT910LdfKcVj1xILyPbCLnJ223UYX1VTaXIzU2Q0ckV0w2ul4lyM5wCDEFr+bcxQbzYL2TpEZu+41/SmYlYXXWW54RGEqLjw8CYDQFtDp0qi3cpo2qgZMSIaikNZGeQSRUn8TzV4P6g+2v33FFxViy3vZz5bAXq2eYoXRmqMzR+kBm+qh917J27tfusF91sSP7JwUmrXdRkXVweQ6u8qu8bdvENudnmKHFmzWSm4h8rWYmvC1i6VGj1Ru/LqBuRa3bc+YB+rQRRbgG1heqQ3g//dRJbVIyqZ7Hxn/8qkJMVzFlbCKQYmN7XHkMolThDj6bGarE2939RPUmA5HHROADNNLgfkcE9sYvYH4iEjUYh6Z87w7IHSc00Vd5K3C8V/+pMumy5wJDYZyEARVsmzOltLZLo1OVNt+0s1BM9vX9r9Oe++fUR69dzhUqSigml8qxjSwGFvBgKYRe+QRd2J1gDXVlbmbvyNyJfuYVVIgL1isXA4awRdiLWo3BNjVnyZNCAv1ZgLkdWgKNBp+Tx4XSGuNx18Lj4Aocn4N7HbA6OkUvJhwFegw==
  template:
    metadata:
      creationTimestamp: null
      name: aws-ecr-secret
      namespace: poncho-namespace
    type: kubernetes.io/dockerconfigjson

