FROM python:3.10-slim as builder

WORKDIR /app

RUN apt-get update && \
    pip install virtualenv

ENV VIRTUAL_ENV=/opt/venv
RUN python -m virtualenv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . .

RUN python manage.py collectstatic --no-input

FROM nginx:stable-alpine3.17 as runner 

COPY --from=builder /app/static /usr/share/nginx/html/static
COPY --from=builder /app/nginx.conf /etc/nginx/nginx.conf
