apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kibana
    targetRevision: "10.9.0"
    helm:
      values: |
        service:
          type: LoadBalancer

        elasticsearch:
          enabled: false
          port: 9200
          hosts: ["elasticsearch.efk.svc.cluster.local"]
          
  destination:
    server: https://kubernetes.default.svc
    namespace: efk

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

