apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
  namespace: poncho-namespace
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWthOSs9ZHg1ZyRAb2d5JSMhKSliLSRwb151KyUheWQqIzUkbTd1Z3p2KGklai05X3El
  ALLOWED_HOSTS: a2luZy1wb25jaG8uYm91bmNlbWUubmV0LHBvbmNoby1hcHBsaWNhdGlvbi1naXQtc2VydmljZS5wb25jaG8tbmFtZXNwYWNlLnN2Yy5jbHVzdGVyLmxvY2FsLGxvY2FsaG9zdA==
  DATABASE_NAME: cG9uY2hvZGI=
  DATABASE_USER: YWRtaW4=
  DATABASE_PASSWORD: YWRtaW5wYXNzd29yZA==
  DATABASE_PORT: MjcwMTc=
  DEBUG: dHJ1ZQ==
  DJANGO_SUPERUSER_EMAIL: a2luZ0BnbWFpbC5jb20=
  DJANGO_SUPERUSER_USERNAME: YWRtaW4=
  DJANGO_SUPERUSER_PASSWORD: YWRtaW4=
